import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius, fontFamily, shadows } from './colors';

export const createAuthStyles = (theme: typeof colors.light) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    scrollContent: {
      flexGrow: 1,
      padding: spacing.lg,
      paddingTop: spacing.xl,
      paddingBottom: spacing.xxxl,
    },
    content: { maxWidth: 400, width: '100%', alignSelf: 'center' },
    header: { marginBottom: spacing.xl, alignItems: 'center' },
    title: {
      fontFamily: fontFamily.bold,
      fontSize: 26,
      letterSpacing: -0.5,
      color: theme.foreground,
      marginTop: spacing.md,
      marginBottom: spacing.xs,
      textAlign: 'center',
    },
    subtitle: {
      fontFamily: fontFamily.regular,
      fontSize: 14,
      color: theme.mutedForeground,
      textAlign: 'center',
      lineHeight: 20,
    },
    form: { gap: spacing.md },
    inputGroup: { gap: spacing.xs },
    label: {
      fontFamily: fontFamily.medium,
      fontSize: 13,
      color: theme.foreground,
    },
    input: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      borderRadius: borderRadius.xl,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm + 4,
      fontFamily: fontFamily.regular,
      fontSize: 15,
      color: theme.foreground,
      backgroundColor: theme.card,
    },
    inputError: { borderColor: theme.destructive },
    passwordWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      borderRadius: borderRadius.xl,
      paddingHorizontal: spacing.md,
      backgroundColor: theme.card,
    },
    passwordWrapFocused: { borderColor: theme.primary },
    passwordInput: {
      flex: 1,
      paddingVertical: spacing.sm + 4,
      fontFamily: fontFamily.regular,
      fontSize: 15,
      color: theme.foreground,
    },
    fieldError: {
      fontFamily: fontFamily.medium,
      fontSize: 12,
      color: theme.destructive,
      marginTop: 2,
    },
    button: {
      backgroundColor: theme.primary,
      paddingVertical: spacing.md,
      borderRadius: borderRadius.full,
      alignItems: 'center',
      marginTop: spacing.sm,
      ...shadows.md,
    },
    buttonDisabled: { opacity: 0.45 },
    buttonText: {
      fontFamily: fontFamily.semibold,
      fontSize: 15,
    },
    dividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginVertical: spacing.xs,
    },
    dividerLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: theme.border },
    dividerText: {
      fontFamily: fontFamily.medium,
      fontSize: 12,
      color: theme.mutedForeground,
    },
    footer: { flexDirection: 'row', justifyContent: 'center', marginTop: spacing.sm },
    footerText: {
      fontFamily: fontFamily.regular,
      fontSize: 14,
      color: theme.mutedForeground,
    },
    link: {
      fontFamily: fontFamily.semibold,
      fontSize: 14,
      color: theme.primary,
    },
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: spacing.lg,
      backgroundColor: theme.card,
      ...shadows.card,
    },
    features: {
      marginTop: spacing.xl,
      paddingTop: spacing.lg,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.border,
      gap: spacing.sm,
    },
    featureRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
    featureDot: {
      fontFamily: fontFamily.bold,
      fontSize: 14,
      color: theme.primary,
      lineHeight: 20,
    },
    featureText: {
      flex: 1,
      fontFamily: fontFamily.regular,
      fontSize: 13,
      lineHeight: 19,
      color: theme.mutedForeground,
    },
    forgotRow: { alignItems: 'flex-end' },
    linkRow: { alignItems: 'center', marginTop: spacing.xs },
    linkText: {
      fontFamily: fontFamily.regular,
      fontSize: 14,
      textAlign: 'center',
      color: theme.mutedForeground,
    },
    outlineButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      minHeight: 48,
      paddingHorizontal: spacing.lg,
      borderRadius: borderRadius.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      backgroundColor: theme.card,
    },
    outlineButtonText: {
      fontFamily: fontFamily.semibold,
      fontSize: 14,
      color: theme.foreground,
    },
    iconWrap: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: spacing.md,
      backgroundColor: theme.muted,
    },
    otpHint: {
      fontFamily: fontFamily.medium,
      fontSize: 12,
      color: theme.destructive,
      textAlign: 'center',
    },
  });
