name: Android Production Release

on:
  push:
    branches: ['main']

jobs:
  build_android:
    name: Build Android Production
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit to Google Play
    needs: [build_android]
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production